## Numpy 
- one of the core packages for numerical computing in python
- many packages are built on top of numpy
-numpy has been optimized for processing: faster due to memory access

In [1]:
#import numpy with standard abbreviation
import numpy as np

### Variables
We can think about variables as a name we assign to a particular object in python. for example

In [2]:
# assign a small array to a variable a
a = np.array ( [ [1,1,2], [3,5,8] ] )

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## Naming variables

In this class, we are going to use `snake_case` for naming variables

# variables and objects

**object** often encountered in python documentation and tutorials

object is a bundle of properties and actions about something specific

Example: 
- object : data frame
- properties: numer of rows, names of columns, data created
- actions: seleting a row, adding a column

A variable isi a name we give a specific object, and the same object can be referenced by different variables 

Exampple: 
- The sun ( actual start) = object
- sol = spanish work for sun = variable
- soleil = french for sun = another variable

In practice: we will use object and variable interchangably

# Types 
Each object in python has a type.

type = what kind of object it is

We can also call the type of the object, the **class** of the object

We can see the type / class of an object by using the `type` function: 

In [6]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object / data type in the NumPy package. we can check the type of the entry in the array by indexing: 

In [8]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [10]:
# how to access value 5 in array a
print(a[1,1])

5


# Functions 
`print` was our example of a python function
a function: 
- take in a set of **arguments**, separated by commas, and 
- use those arguments to produce some **output**

argument = parameter 

We can ask information about a function by executing `?` followed by the function name


In [11]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in parenthesis
- then a short description of what the function does]
- finally , a list of the arguments and a brief explanation of each of them

Different types of arguments inside the parenthesis. Roughly speaking, there are two types of arguemnts: 

- **non-optional**: arguments you need to specify for the function to do something
- **optional** : arguments that are pre filled with a default value by the function, but we can override them. Optional arguments appear inside the parenthesis () in the form 

`optional argument = default value`

In [12]:
print('chagning the default end argument of the print function', end = ':)')

chagning the default end argument of the print function:)

# Attributes and Methods

An object in python has attributes and methods. 
- **attributes**: a property of an object, a piece of information about it. 
- **method**: a procedure associated with an object, an action where the main ingreedient is the object itself

Access a variable's atrributes and methods by adding a period `.` at the end of the variables name

`variable.variable_method()` or
`variable.variable_attribute`

Examples: 
Methods and attributes of numpy arrays: 

In [1]:
import numpy as np

In [2]:
#define a 3x3 array

var = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# shape: an attribute telling us the number of elements in each dimmension of the array
var.shape

(3, 3)

In [4]:
type(var.shape)

tuple

In [5]:
#ndim is an attribute holding the number of array dimmensions

var.ndim

2

In [6]:
type(var.ndim)

int

# R & Python
R:
-doesnt use methods within an object
functions in R are extrinsinc to(outside) the object they are acting on

Example: recreate getting the min value in an array

In R there would be two seprate items : the variable `var` as a parameter:

```
#this is R code
var <- array(c(1,4,7,2,5,8,3,6,9) , dim(c(3,3) )
min(var)
```

using the pipe operator %>% in R's tidyverse is closer to the `.` in python:

```
var <- array(c(1,2,3,4,5,6,7,8,9), dim = c(3,3))
var %>% min()

```

What is happening?
the pipe `%>%` is passing `var` to the `min()` as it first argument. This is essentially the `.` in python
